/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Feed {
  feedType: FeedType
  id: string
  updated?: number
  authors: Array<string>
  description?: string
  links: Array<string>
  categories: Array<string>
  contributors: Array<string>
  generator?: string
  icon?: Image
  language?: string
  logo?: Image
  published?: number
  rating?: MediaRating
  rights?: string
  ttl?: number
  entries: Array<Entry>
}
export const enum FeedType {
  Atom = 'Atom',
  JSON = 'JSON',
  RSS0 = 'RSS0',
  RSS1 = 'RSS1',
  RSS2 = 'RSS2',
}
export interface Entry {
  id: string
  title?: string
  updated?: number
  authors: Array<string>
  content?: Content
  links: Array<string>
  summary?: string
  categories: Array<string>
  contributors: Array<string>
  published?: number
  source?: string
  rights?: string
  media: Array<MediaObject>
}
export interface Image {
  uri: string
  title?: string
  link?: string
  width?: number
  height?: number
  description?: string
}
export interface MediaContent {
  url?: string
  contentType?: string
  height?: number
  width?: number
  duration?: number
  size?: number
  rating?: MediaRating
}
export interface MediaRating {
  urn: string
  value: string
}
export interface Content {
  body?: string
  contentType: string
  length?: number
  src?: string
}
export interface MediaObject {
  title?: string
  content: Array<MediaContent>
  duration?: number
  thumbnails: Array<Image>
  texts: Array<string>
  description?: string
  credits: Array<string>
}
export function parse(feedString: string, feedSource?: string | undefined | null): Feed
