/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Feed {
  feedType: FeedType
  id: string
  title?: Text
  updated?: number
  authors: Array<Person>
  description?: Text
  links: Array<Link>
  categories: Array<Category>
  contributors: Array<Person>
  generator?: Generator
  icon?: Image
  language?: string
  logo?: Image
  published?: number
  rating?: MediaRating
  rights?: Text
  ttl?: number
  entries: Array<Entry>
}
export interface Generator {
  content: string
  uri?: string
  version?: string
}
export interface Link {
  href: string
  rel?: string
  mediaType?: string
  hrefLang?: string
  title?: string
  length?: number
}
export interface Category {
  term: string
  scheme?: string
  label?: string
}
export interface Person {
  name: string
  uri?: string
  email?: string
}
export const enum FeedType {
  Atom = 'Atom',
  JSON = 'JSON',
  RSS0 = 'RSS0',
  RSS1 = 'RSS1',
  RSS2 = 'RSS2',
}
export interface Text {
  contentType: string
  src?: string
  content: string
}
export interface Entry {
  id: string
  title?: Text
  updated?: number
  authors: Array<Person>
  content?: Content
  links: Array<Link>
  summary?: Text
  categories: Array<Category>
  contributors: Array<Person>
  published?: number
  source?: string
  rights?: Text
  media: Array<MediaObject>
}
export interface Image {
  uri: string
  title?: string
  link?: string
  width?: number
  height?: number
  description?: string
}
export interface MediaContent {
  url?: string
  contentType?: string
  height?: number
  width?: number
  duration?: number
  size?: number
  rating?: MediaRating
}
export interface MediaRating {
  urn: string
  value: string
}
export interface Content {
  body?: string
  contentType: string
  length?: number
  src?: string
}
export interface MediaObject {
  title?: Text
  content: Array<MediaContent>
  duration?: number
  thumbnails: Array<MediaThumbnail>
  texts: Array<MediaText>
  description?: Text
  community?: MediaCommunity
  credits: Array<MediaCredit>
}
export interface MediaCommunity {
  starsAvg?: number
  starsCount?: number
  starsMin?: number
  starsMax?: number
  statsViews?: number
  statsFavorites?: number
}
export interface MediaText {
  text: Text
  startTime?: number
  endTime?: number
}
export interface MediaThumbnail {
  image: Image
  time?: number
}
export interface MediaCredit {
  entity: string
}
export function parse(feedString: string, feedSource?: string | undefined | null): Feed
